// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import {Call} from '@wailsio/runtime';
export async function GetVersion() : Promise<string> {
	return Call.ByName("main.TwsnmpMWService.GetVersion");
}

